os: osx
language: generic
osx_image: xcode8.3
before_script:
  - pip install six
  - brew update
  - brew install --HEAD libimobiledevice
  - brew install ideviceinstaller
  - brew install ios-deploy
  - git clone https://github.com/flutter/flutter.git -b alpha --depth 1
script:
  - ./flutter/bin/flutter -v build ios --no-codesign

cache:
  directories:
    - $HOME/.pub-cache